FROM node:14.17.1-alpine



WORKDIR /usr/src/app

COPY ./packages/back/package.json ./
COPY yarn.lock ./
RUN yarn install 
RUN yarn  global add typescript
RUN yarn  global add copyfiles

COPY ./packages/back ./

RUN yarn run build

EXPOSE 7000
CMD [ "yarn", "start" ]