FROM node:14.17.1-alpine as build
WORKDIR /app
COPY ./packages/front/package.json ./
COPY ./yarn.lock ./
RUN yarn install
RUN yarn global add react-scripts
RUN yarn global add sass
COPY ./packages/front ./
RUN yarn run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]